import "~/styles/globals.css";
import { Dosis, Jost, Raleway } from "next/font/google";
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/components/ui/toaster";
import { Header } from "~/app/_components/header/header";

const jost = Jost({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-jost",
});

const dosis = Dosis({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dosis",
});
const raleway = Raleway({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Mountain view hotel",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${jost.variable} ${dosis.variable} ${raleway.variable}`}
    >
      <body className="grid grid-cols-12">
        <Header />
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
